name: Audit

# run audit checks once per day
on:
  schedule:
    - cron: '43 2 * * *'

jobs:

  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cameronfyfe/install-nix-action@v19
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Nix Shell
        run: nix develop -L -c true
      - name: Cargo Audit
        run: nix develop -c cargo audit
