name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: eqtylab-actions/install-nix-action@v19
      - uses: eqtylab-actions/checkout@v3
      - run: nix develop -L -c true
      - run: nix develop -c cargo risczero install
      - run: nix develop -c ets -sc just ci
